### DISCUSSION TITLE
Cache not found for input keys

### DISCUSSION THREAD

**Discussion by tmhererwa** [terraform-linters/setup-tflint#163] [Q&A] [answered]
Cache plugin dir step failing 

`Run actions/cache@v3
  with:
    path: ~/.tflint.d/plugins
    key: ubuntu-latest-tflint-
    enableCrossOsArchive: false
    fail-on-cache-miss: false
    lookup-only: false
  env:
    TF_LOG: INFO
    TERRAFORM_CLI_PATH: /home/runner/work/_temp/caef4[2](https://github.com/my-repo/root-dir/actions/runs/4786210260/jobs/8509878101#step:8)
Cache not found for input keys: ubuntu-latest-tflint-`

This leads to below error:

`Run terraform-linters/setup-tflint@v3
  with:
    tflint_version: 0.44.1
    github_token: ***
  env:
    TF_LOG: INFO
    TERRAFORM_CLI_PATH: /home/runner/work/_temp/caef4[2](https://github.com/bison-cloud-platform/my-repo/root-dir/actions/runs/4786210260/jobs/8509878101#step:9)
Error: Error: Unexpected HTTP response: 404
Error: Unexpected HTTP response: 404`

The terraform.yaml file config applicable to tflint is as shown below:
```
 # Lint using TFLint
      - name: Cache plugin dir
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: 0.44.1

      - name: Show tflint version
        run: tflint --version

      - name: Init tflint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ secrets.TFLINT_TOKEN }}

      - name: Run tflint
        run: tflint -f compact
```

**Comment by bendrucker** [comment, marked as answer]
The output of `hashFiles('.tflint.hcl')` is missing from your key so it seems like you don't have a `.tflint.hcl` file in your working directory. `actions/checkout` is required first if you haven't included that.

**Reply by tmhererwa** [reply]
Thank you @bendrucker. I had `actions/checkout@v3` before the `actions/cache@v3` but the issue was the indeed missing `.tflint.hcl` in my repo base dir.

I am now trying to resolve the Github 404 issue. Somehow it is failing to access the repo to list and download revisions. I added GITHUB_TOKEN secret, but something is amiss.

**Comment by piankris** [comment]
Confirming on the issue.

My setup:

```
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: snok/install-poetry@v1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true
                  installer-parallel: true
            - uses: actions/setup-python@v4
              id: setup-python
              with:
                  python-version: '3.10'
            - name: Load cached venv
              id: cached-dependencies
              uses: actions/cache@v3
              with:
                  path: |
                      .venv
                      ~/.cache/pre-commit
                      ~/.tflint.d/plugins
                  key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
                      pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}tflint-${{ hashFiles('.tflint.hcl') }}
            - name: Install dependencies
              if: steps.cached-dependencies.outputs.cache-hit != 'true'
              run: poetry install --no-interaction --no-root
            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v35
            - name: List all changed files
              run: |
                for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                    echo "$file was changed"
                done
            - name: Install pre-commit hooks
              if: steps.cached-dependencies.outputs.cache-hit != 'true'
              run: |
                  source .venv/bin/activate
                  pre-commit install-hooks
            - name: Setup TFLint
              if: steps.cached-dependencies.outputs.cache-hit != 'true'
              uses: terraform-linters/setup-tflint@v3
              with:
                  tflint_version: v0.44.1
            - name: Run pre-commit
              env:
                  HOOKS_TO_SKIP: sqlfluff-fix,sqlfluff-lint,terraform_fmt,terrascan
              run: |
                  source .venv/bin/activate
                  SKIP=$HOOKS_TO_SKIP pre-commit run --files ${{ steps.changed-files.outputs.all_changed_files }}
```
