### ISSUE TITLE
Handle cache and init internally

### ISSUE THREAD

**Issue by lukasz-mitka** [terraform-linters/setup-tflint#161]
Instead of requiring users to setup cache and call init just do it as part of this action.

```yaml
    - uses: actions/cache@v3
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v3
      name: Setup TFLint
      with:
        tflint_version: v0.44.1

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init
      env:
        # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
        GITHUB_TOKEN: ${{ github.token }}
```

Could become
```yaml
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: v0.44.1
```
* cache - see https://github.com/actions/setup-node/blob/main/src/cache-save.ts and similar.
* token - already provided to `terraform-linters/setup-tflint` action
* version - just run it so it's visible in logs and set as output
* additional settings - allow users to disable caching, init or to provide custom cache key.
