### ISSUE TITLE
prevent job from failing when there are only warnings

### ISSUE THREAD

**Issue by kaykhan** [terraform-linters/setup-tflint#172]
How can i prevent the job from failing when there are only warnings showing, i only want it to fail when there is an error.

```
jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Terraform Format
      id: format
      run: terraform fmt -check -recursive
  lint:
    needs: format
    name: lint 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: terraform-linters/setup-tflint@v3
      name: Setup TFLint
      with:
        tflint_version: v0.44.1
    - name: Show version
      run: tflint --version
    - name: Init TFLint
      run: tflint --init
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Run TFLint
      run: tflint
```

![image](https://github.com/terraform-linters/setup-tflint/assets/5202527/f6ad8dd2-7176-48a7-8766-2543c37cf14d)
