### ISSUE TITLE
Wrapper issue

### ISSUE THREAD

**Issue by mission-bsakowski** [terraform-linters/setup-tflint#187]
When trying to use the wrapper functionality on v3 of the action, no stdout is produced, and there is a warning from the job that the argument is invalid.

<img width="712" alt="CleanShot 2023-08-23 at 16 15 47@2x" src="https://github.com/terraform-linters/setup-tflint/assets/106995816/7702ec00-bfbf-4926-9c4c-9bfc7b53043d">

Workflow code:

```yaml
- uses: terraform-linters/setup-tflint@v3
  name: Setup TFLint
  with:
    tflint_wrapper: true
```
